branches:
  only:
  - master
  - devel

env:
  global:
  - RGL_USE_NULL=TRUE
  - PKG_CFLAGS="-O3 -Wall -pedantic"

language: R
sudo: required
cache: packages

cran: http://cran.rstudio.com
warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-build-vignettes --no-manual"

r:
  - release
  - devel

addons:
  apt:
    - sources:
      - deadsnakes
    - packages:
      - libx11-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - libmysqlclient-dev
      - python3.6
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --upgrade pip setuptools
  - pip3 install --quiet --ignore-installed numpy tensorflow keras

r_packages:
  - devtools
  - covr
  - sessioninfo
  - data.table
  - hal9001
  - delayed

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo
  - tlverse/origami
  - nhejazi/haldensify

after_success:
  - travis_wait 80 Rscript -e 'covr::codecov()'

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
