branches:
  only:
  - master
  - devel

env:
  global:
  - RGL_USE_NULL=TRUE
  - PKG_CFLAGS="-O3 -Wall -pedantic"

language: r
sudo: required
cache: packages

cran: "http://cran.rstudio.com"
warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - release
  - devel

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip install numpy tensorflow keras

r_packages:
  - devtools
  - covr
  - drat

script:
  #- Rscript -e "devtools::install_github(c('osofr/condensier',
                                           #'tlverse/delayed',
                                           #'tlverse/origami',
                                           #'tlverse/hal9001'),
                                           #upgrade_dependencies = FALSE)"

r_github_packages:
  - r-lib/devtools@2d012d1
  - r-lib/sessioninfo
  - jimhester/covr
  - osofr/simcausal
  - osofr/condensier
  - tlverse/delayed
  - tlverse/origami
  - tlverse/hal9001

after_success:
  - travis_wait 80 Rscript -e 'covr::codecov()'

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change

