language: r
dist: trusty
sudo: required
cache: packages
warnings_are_errors: true
r_check_args: ''

r:
  - release
  - devel

env:
  global:
    - RGL_USE_NULL=TRUE
    - PKG_CFLAGS="-O3 -Wall -pedantic"
    - secure: "nCJS8SflaaailfQ/QEt5wW36HBFMhti4KbMKOrcFSJ6wi9K7n8K6WzTjrZ+RfPMVZjsiSjNcWseGCnr+Yyl+yKW7jIm0ZDOAdMY3LCqTBlh6hrmReH2bto6qrlG1yXZYNWaIrPYXCOjDWJc/MU9F24g+MmppFl+n7O36caOLb96mLBGJXkoCo5Tuz9dCd4mFi4x9kw/hwFyrblgVEPsjHZiJDQlaU63dRNWomt3fEaIlhNPZTFWMuR7u2ciWoZpwgzbhcFDe9oMsYfu/nbZPEEIZgo6V6D3EwmeMm+NUy4LmIpNWmOMSkuFrywJuUErPEKevf2TIWDeykt84cuY/y6DXvJWGY1JRfXrxWoAfyybnUd+2Raby3sCGhBrAwSexUhIXpIR4quOfmgz7kIhwU2GRkifryWWFJHlmYaGoJtbl6xYS7PCxRt20yH9m1Ap7T4F+8oe3iqBaPrWGnqDoafy3iPz/fzqhb3xMjMM0C7mvOUNYLFFruXIaritn6iKlSdHEPuQ2scNSbjuI0YLUzS6I2kJbOBQwBipQzvWxY1EWjyQ3M/2BnusKjGn6qgpDEElYyPDEn/RncBbEMVqGH+Bm1J7MHV6aG8wMxRT/svGFJHyzngTDNU0Do25eCjQkDeBEUUFHEO7KGEkCSZKk6J/pyhNDzTr/Uc4ttmBBIv4="

before_install: Rscript -e 'update.packages(ask = FALSE)'
  - sudo apt-get -y install python3-pip python-dev
  - pip3 install numpy 
 
install:
  - sudo pip3 install -U tensorflow
  - sudo pip3 install -U keras

r_packages:
  - covr
  - drat

r_github_packages:
  - jimhester/covr

after_success:
  - travis_wait Rscript -e 'covr::codecov()'
  - test $TRAVIS_REPO_SLUG == "jeremyrcoyle/sl3" &&
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash deploy.sh

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
